/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 chair.gltf --transform 
Files: chair.gltf [113.62KB] > chair-transformed.glb [71.16KB] (37%)
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sofa-chair-0e8e009f398249b9bc13e8ff7078530a
Title: Sofa Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/chair-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_4.geometry}
				material={materials["Material.001"]}
				scale={[0.944, 1, 1]}
			/>
			<mesh
				geometry={nodes.Object_10.geometry}
				material={materials["Material.002"]}
				position={[0, 0.017, 0]}
			/>
			<mesh
				geometry={nodes.Object_12.geometry}
				material={materials.material_0}
				position={[0.006, 0.678, -0.478]}
				rotation={[1.24, -0.013, -0.104]}
				scale={[0.4, 0.294, 0.354]}
			/>
		</group>
	);
}

useGLTF.preload("/chair-transformed.glb");
