/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 cappuccino.gltf --transform 
Files: cappuccino.gltf [19.13MB] > cappuccino-transformed.glb [1.17MB] (94%)
Author: Elen (https://sketchfab.com/Kitty999)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/cup-of-cappuccino-04f2c34a3df94e58be97c2830e7e462a
Title: Cup of cappuccino
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/cappuccino-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_31.geometry}
				material={materials.Coffee}
				position={[0.001, 0.082, 0]}
				rotation={[-Math.PI, 1.031, -Math.PI]}
			/>
			<mesh
				geometry={nodes.Object_33.geometry}
				material={materials.material}
				position={[0, 0.005, 0]}
			/>
			<mesh
				geometry={nodes.Object_35.geometry}
				material={materials.Plate}
				position={[0.001, 0, 0]}
			/>
			<instancedMesh
				args={[nodes.Object_0.geometry, materials.Marshmallow, 13]}
				instanceMatrix={nodes.Object_0.instanceMatrix}
			/>
		</group>
	);
}

useGLTF.preload("/cappuccino-transformed.glb");
