/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 flatWhite.gltf --transform 
Files: flatWhite.gltf [12.53MB] > flatWhite-transformed.glb [506.85KB] (96%)
Author: Elen (https://sketchfab.com/Kitty999)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-with-plate-c3132a723f434ce2b94e2e563420ef7a
Title: Coffee cup with plate
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/flatWhite-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.Object_5.geometry}
				material={materials.Coffee}
				position={[0, 0.069, 0]}
			/>
			<mesh
				geometry={nodes.Object_7.geometry}
				material={materials.material}
				position={[0, 0.003, 0]}
			/>
			<mesh
				geometry={nodes.Object_9.geometry}
				material={materials.Plate}
				position={[0.002, 0.001, 0]}
			/>
		</group>
	);
}

useGLTF.preload("/flatWhite-transformed.glb");
