/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.12 latte.gltf --transform 
Files: latte.gltf [33.47MB] > latte-transformed.glb [6.47MB] (81%)
Author: Pixel Bee (https://sketchfab.com/PixelBee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-cb9cfeed4e244971b32194b6013bbf76
Title: Coffee Cup
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
	const { nodes, materials } = useGLTF("/latte-transformed.glb");
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes.cup1_lambert2_0.geometry}
				material={materials.lambert2}
				scale={0.099}
			/>
			<mesh
				geometry={nodes.cup2_lambert3_0.geometry}
				material={materials.lambert3}
				scale={0.099}
			/>
			<mesh geometry={nodes.cup4_bmat_0.geometry} material={materials.bmat} scale={0.099} />
			<mesh
				geometry={nodes.cup5_lambert4_0.geometry}
				material={materials.lambert4}
				scale={0.099}
			/>
		</group>
	);
}

useGLTF.preload("/latte-transformed.glb");
